config/routes.rb
Rails.application.routes.draw do
   resources :students
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def new
  end
    
  def create
    render plain: params[:student].inspect
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TigersDen</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/index.html.erb
 
<h1>Student Sign-up</h1>
<p>Find me in app/views/students/index.html.erb</p>
   <form action=" ">
       <style></style>
    Name:<br>
    <input type = "text" name = "fullname"placeholder = "Enter your name"><br>
    <label for="email">Email:</label><br>
    <input id="email" type ="email" name = "email" placeholder = "Enter your email"> <br>
    <label for="password">Password:</label><br>
    <input id="password" type = "password" name = "password"placeholder = "Enter your password"> <br>  
    <button type = "submit">submit</button> 
</form>

app/views/students/new.html.erb
 
<h1>Student Sign-up this is new</h1>
<%= form_with scope: :student, url: students_path, local: true do |form| %> 
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :email %><br>
    <%= form.text_area :email %>
  </p>
  <p>
    <%= form.submit %>   
  </p>
<% end %>